version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/amazing-booking-nestjs
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 30000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30000
      runas: ec2-user
