version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/amazing-booking-nestjs
    overwrite: true
    ignoreHiddenFiles: true
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3000
      runas: ec2-user
